"use client";
import Link from "next/link";
import {FormEvent,useMemo,useState} from "react";
import {createFoodOrder,type OrderItem} from "@/lib/firebase/data";
import {lateNightDeals} from "@/lib/boemo/menu";
const baseItems:OrderItem[]=lateNightDeals.map(deal=>({name:deal.name,price:deal.price,quantity:0}));
export default function OrderForm(){
 const[items,setItems]=useState(baseItems),[submitted,setSubmitted]=useState(false),[reference,setReference]=useState(""),[pendingSync,setPendingSync]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const selected=useMemo(()=>items.filter(item=>item.quantity>0),[items]); const total=selected.reduce((sum,item)=>sum+item.price*item.quantity,0);
 function change(name:string,delta:number){setItems(current=>current.map(item=>item.name===name?{...item,quantity:Math.max(0,item.quantity+delta)}:item))}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;if(!selected.length){setError("Choose at least one food item.");return}setBusy(true);setError("");const form=new FormData(event.currentTarget);const order={createdAt:new Date().toISOString(),customerName:String(form.get("customerName")??"").trim(),phone:String(form.get("phone")??"").trim(),mode:String(form.get("mode")??"pickup") as "pickup"|"delivery",scheduledFor:String(form.get("scheduledFor")??""),deliveryLocation:String(form.get("deliveryLocation")??"").trim(),instructions:String(form.get("instructions")??"").trim(),items:selected.map(({name,price,quantity})=>({name,price,quantity})),total,status:"New" as const};if(!order.customerName||!order.phone||!order.scheduledFor){setError("Please add your name, phone and preferred time.");setBusy(false);return}if(order.mode==="delivery"&&!order.deliveryLocation){setError("Add your delivery location or landmark.");setBusy(false);return}try{const offline=!navigator.onLine;const{id,writePromise}=createFoodOrder(order);setReference(id.slice(0,8).toUpperCase());if(offline){void writePromise.catch(console.error);setPendingSync(true)}else{const synced=await Promise.race([writePromise.then(()=>true),new Promise<boolean>(resolve=>window.setTimeout(()=>resolve(false),8000))]);if(!synced)setPendingSync(true)}setSubmitted(true);event.currentTarget.reset()}catch{setError("The order was not confirmed. Please try again or call BOEMO on 76425849 / 76769834.")}finally{setBusy(false)}}
 if(submitted)return <main className="orderPage"><div className="orderWrap"><div className="orderCard confirm"><div className="confirmIcon">🍔</div><span className="kicker">{pendingSync?"Offline save":"Order submitted"}</span><h1>{pendingSync?"Saved on this phone.":"Order received."}</h1><p>{pendingSync?"Your order is waiting to synchronize. Reconnect this device so it can reach BOEMO. Until then, the kitchen has not received it.":"Your order was written to the BOEMO order queue. The kitchen can review it and contact you if needed."}</p><strong>Reference #{reference}</strong><div className="actions centered"><Link className="button buttonPrimary" href="/">Back to BOEMO</Link><a className="button buttonLight" href="tel:76425849">Call BOEMO</a></div></div></div></main>;
 return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="logo"><span className="logoMark">B</span><span>BOEMO</span></Link><Link href="/" className="button buttonLight">Back</Link></div><div className="sectionHead"><div><span className="kicker">Order ahead</span><h1>Choose your food.</h1><p>Pick your items, choose pickup or delivery and tell us when you need it.</p></div></div><form onSubmit={submit} className="orderGrid"><div className="orderCard"><h2>Menu & deals</h2><div className="orderItems">{items.map(item=><article className="orderItem" key={item.name}><div><strong>{item.name}</strong><small>P{item.price.toFixed(item.price%1?1:0)}</small></div><div className="qty"><button type="button" onClick={()=>change(item.name,-1)} aria-label={"Remove "+item.name}>−</button><strong>{item.quantity}</strong><button type="button" onClick={()=>change(item.name,1)} aria-label={"Add "+item.name}>+</button></div></article>)}</div><p className="orderTruth">Weekly food is shown on the BOEMO home screen. Deal prices here are the supplied current deal list.</p></div><div className="orderCard"><h2>Your order</h2><div className="fieldGrid"><label>Name<input name="customerName" autoComplete="name" required/></label><label>Phone / WhatsApp<input name="phone" type="tel" autoComplete="tel" required/></label><label>When do you need it?<input name="scheduledFor" type="datetime-local" required/></label><label>Order type<select name="mode" defaultValue="pickup"><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select></label><label className="fieldFull">Delivery location / landmark <span>(required for delivery)</span><input name="deliveryLocation" placeholder="BAC Library, main entrance..."/></label><label className="fieldFull">Instructions <span>(optional)</span><textarea name="instructions" placeholder="Call when outside, no onions, etc."/></label></div><div className="total"><span>Total</span><strong>P{total.toFixed(2)}</strong></div>{error&&<p role="alert" className="notice">{error}</p>}<button className="button buttonPrimary" type="submit" disabled={busy||!selected.length}>{busy?"Saving order…":"Place order"}</button></div></form></div></main>
}