"use client";
import Link from "next/link";
import {GoogleAuthProvider,linkWithPopup,onAuthStateChanged,signInWithPopup,type User} from "firebase/auth";
import {useEffect,useState} from "react";
import {auth} from "@/lib/firebase/client";
import {getFoodOrder,isAdminUser,subscribeToFoodOrder,type FoodOrder} from "@/lib/firebase/data";
import {downloadReceiptPdf} from "@/lib/boemo/receipt";
function statusText(status:FoodOrder["status"]){return status==="New"?"Order received":status}
function authMessage(error:unknown){const code=typeof error==="object"&&error&&"code" in error?String((error as {code?:unknown}).code):"";if(code==="auth/unauthorized-domain")return `Google sign-in is not enabled for ${window.location.hostname} yet. Add this website to Firebase Authentication → Settings → Authorized domains.`;return error instanceof Error?error.message:"Google sign-in could not be completed."}
function orderAccessMessage(error:unknown){const code=typeof error==="object"&&error&&"code" in error?String((error as {code?:unknown}).code):"";if(code==="permission-denied"||code==="firestore/permission-denied")return "This order is tied to the customer session that placed it. Reopen the order on the same device/browser, or connect that guest session to Google from My BOEMO.";return error instanceof Error?error.message:"We could not load this order."}
export default function OrderTrackingPage({params}:{params:Promise<{id:string}>}){
 const[order,setOrder]=useState<FoodOrder|null>(null),[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;let stop=()=>{};let firstAuth=true;const unsubscribe=onAuthStateChanged(auth,next=>{setUser(next);if(!firstAuth)return;firstAuth=false;void params.then(async ({id})=>{if(!active)return;try{if(!next){setError("This order needs the same guest session used when it was placed. Open the tracking link on that device/browser, or sign in from My BOEMO if the guest session was already connected to Google.");return}const found=await getFoodOrder(id);if(!found){setError("That BOEMO order could not be found. Check the tracking link or open My BOEMO.");return}setOrder(found);stop=subscribeToFoodOrder(id,nextOrder=>setOrder(nextOrder),err=>setError(orderAccessMessage(err)));}catch(err){setError(orderAccessMessage(err))}finally{setLoading(false)}})});return()=>{active=false;unsubscribe();stop()}},[params]);
 async function google(){try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});if(user?.isAnonymous)await linkWithPopup(user,provider);else await signInWithPopup(auth,provider)}catch(err){setError(authMessage(err))}}
 const owns=Boolean(order?.customerId&&user?.uid===order.customerId);
 return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="logo"><span className="logoMark">B</span><span>BOEMO</span></Link><Link href="/account" className="button buttonLight">My BOEMO</Link></div><section className="orderCard" style={{maxWidth:760,margin:"0 auto"}}>{loading?<div className="emptyState">Loading your order…</div>:error?<><span className="kicker">BOEMO order</span><h1>Order unavailable.</h1><p>{error}</p><p className="orderTruth">Order details are only available to the customer account attached to this order.</p><Link className="button buttonPrimary" href="/account">Go to My BOEMO</Link></>:order?<><span className="kicker">Live order tracking</span><h1>#{order.id.slice(0,8).toUpperCase()}</h1><div className="stats"><article><span>Status</span><strong>{statusText(order.status)}</strong></article><article><span>Total</span><strong>P{order.total.toFixed(2)}</strong></article></div><p>Requested for <strong>{new Date(order.scheduledFor).toLocaleString()}</strong> · {order.mode==="delivery"?"Delivery":"Pickup"}</p>{order.mode==="delivery"&&<p>📍 {order.deliveryLocation}</p>}<section style={{marginTop:24}}><h2>Order progress</h2><div className="queue">{["New","Accepted","Preparing","Ready",order.mode==="delivery"?"Delivering":"Collected",order.mode==="delivery"?"Delivered":"Collected"].filter((v,i,a)=>a.indexOf(v)===i).map(step=><div className="queueRow" key={step}><strong>{step}</strong><span>{step===order.status?"Current":(["New","Accepted","Preparing","Ready","Delivering","Collected","Delivered"].indexOf(step)<["New","Accepted","Preparing","Ready","Delivering","Collected","Delivered"].indexOf(order.status)?"Done":"Waiting")}</span></div>)}</div></section><section style={{marginTop:24}}><h2>Items</h2>{order.items.map(item=><p key={item.name}>{item.quantity} × {item.name} — P{(item.price*item.quantity).toFixed(2)}</p>)}</section><div className="actions"><button className="button buttonPrimary" type="button" onClick={()=>downloadReceiptPdf(order)}>Download PDF receipt</button><button className="button buttonLight" type="button" onClick={()=>window.print()}>Print</button></div>{!owns&&<div className="notice"><strong>Make this your account.</strong><p>Sign in with Google to connect this guest order to a durable BOEMO account. A same-device guest session can be upgraded without losing the order association.</p><button className="button buttonLight" type="button" onClick={()=>void google()}>Continue with Google</button></div>}</>:null}</section></div></main>;
}
