import Image from "next/image";
import Link from "next/link";
import { menuByDay, lateNightDeals } from "@/lib/boemo/menu";

const heroImage = "/boemo-assets/WhatsApp Image 2026-09-23 at 14.12.46.jpeg";
const serviceImage = "/boemo-assets/WhatsApp Image 2026-09-23 at 14.16.14.jpeg";

export default function Home() {
  const today = new Intl.DateTimeFormat("en-US", { weekday: "long" }).format(new Date());
  const todayItems = menuByDay[today] ?? menuByDay.Monday;
  return <main className="boemoSite">
    <div className="topbar"><div className="container topbarInner"><span>BOEMO JOOS DEALER</span><strong>Good Food. Great Taste. Every Day!</strong><span>76425849 · 76769834</span></div></div>
    <nav className="nav"><div className="container navInner"><Link href="/" className="logo"><span className="logoMark">B</span><span>BOEMO</span></Link><div className="navLinks"><a href="#today">Today</a><a href="#deals">Deals</a><a href="#where">Where we are</a></div><Link href="/order" className="button buttonPrimary">Order ahead</Link></div></nav>
    <section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow">BOEMO JOOS DEALER</span><h1>Good food.<br /><em>Big flavour.</em></h1><p>Fresh local comfort food, street-food favourites and student-friendly deals. See what&apos;s cooking and order ahead before you leave class.</p><div className="actions"><Link href="/order" className="button buttonPrimary">Order food</Link><a href="#today" className="button buttonLight">See today&apos;s food</a></div><div className="heroPill"><span>📍</span><div><strong>Mobile kitchen</strong><small>Serving around BAC and nearby student areas</small></div></div></div><div className="heroVisual"><Image src={heroImage} alt="BOEMO food being prepared and served" fill priority sizes="(max-width: 800px) 100vw, 48vw" /></div></div></section>
    <section id="today" className="section"><div className="container"><div className="sectionHead"><div><span className="kicker">Today&apos;s food · {today}</span><h2>What&apos;s cooking?</h2></div><Link href="/order" className="textLink">Order ahead →</Link></div><div className="menuStrip">{todayItems.map(item => <article className="menuCard" key={item}><span>🍽️</span><strong>{item}</strong></article>)}</div><p className="truthNote">Menu shown from BOEMO&apos;s current supplied weekly menu. Availability can change during service.</p></div></section>
    <section id="deals" className="section dealsSection"><div className="container"><div className="sectionHead"><div><span className="kicker">Late night · deals</span><h2>Bring a friend. Save.</h2></div><Link href="/order" className="textLink">Start an order →</Link></div><div className="dealGrid">{lateNightDeals.map(deal => <article className="dealCard" key={deal.name}><div><strong>{deal.name}</strong>{deal.friend && <small>Bring a Friend: P{deal.friend}</small>}</div><b>P{deal.price}</b></article>)}</div></div></section>
    <section className="section storySection"><div className="container storyGrid"><div className="storyImage"><Image src={serviceImage} alt="BOEMO takeaway meal with burger and chips" width={1000} height={1000} sizes="(max-width: 800px) 100vw, 45vw" /></div><div><span className="kicker">Between classes?</span><h2>Can&apos;t leave class?</h2><p>Choose your food, tell us when you want it and choose pickup or delivery. We&apos;ll have your order details ready for the kitchen.</p><Link href="/order" className="button buttonPrimary">Plan my order</Link></div></div></section>
    <section id="where" className="section locationSection"><div className="container locationGrid"><div><span className="kicker">Mobile kitchen</span><h2>Find BOEMO today.</h2><p>BOEMO is a mobile kitchen, so the operating location can change. Check with BOEMO for the current spot and serving hours before travelling.</p><div className="contactRow"><a className="button buttonDark" href="tel:76425849">Call 76425849</a><a className="button buttonLight" href="tel:76769834">Call 76769834</a></div></div><div className="locationCard"><span>📍</span><strong>Today&apos;s location</strong><p>Current location and serving hours will be published here as BOEMO configures the operating schedule.</p><small>No fixed restaurant address is assumed.</small></div></div></section>
    <footer className="footer"><div className="container footerInner"><div><strong>BOEMO Joos Dealer</strong><span>We Cook. You Enjoy!</span></div><Link href="/order" className="button buttonPrimary">Order ahead</Link></div></footer>
  </main>;
}