"use client";
import {onAuthStateChanged,signInWithEmailAndPassword,signOut,type User} from "firebase/auth";
import {doc,getDoc} from "firebase/firestore";
import {useEffect,useState} from "react";
import {auth,db} from "@/lib/firebase/client";
export default function AdminGate({children}:{children:React.ReactNode}){
 const[user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true),[authorized,setAuthorized]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,async next=>{setUser(next);if(!next){setAuthorized(false);setChecking(false);return}try{const role=await getDoc(doc(db,"admins",next.uid));const allowed=role.exists()&&["owner","staff"].includes(String(role.data().role));setAuthorized(allowed);if(!allowed)await signOut(auth)}catch{setAuthorized(false);await signOut(auth)}finally{setChecking(false)}}),[]);
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const credential=await signInWithEmailAndPassword(auth,email.trim(),password);const role=await getDoc(doc(db,"admins",credential.user.uid));if(!role.exists()||!["owner","staff"].includes(String(role.data().role))){await signOut(auth);throw new Error("This account is not enabled for BOEMO Kitchen.")}setAuthorized(true)}catch(err){setError(err instanceof Error?err.message:"We could not sign you in. Check your details.")}finally{setBusy(false)}}
 if(checking)return <main className="adminPage"><div className="adminShell"><div className="emptyState"><div>🔐</div><h1>Opening BOEMO Kitchen</h1><p>Checking access…</p></div></div></main>;
 if(user&&authorized)return <div className="adminAuthorized"><div className="adminAccountBar"><span>BOEMO Kitchen · {user.email??"authorized staff"}</span><button className="button buttonLight" type="button" onClick={()=>void signOut(auth)}>Sign out</button></div>{children}</div>;
 return <main className="adminPage"><div className="adminShell"><section className="adminPanel" style={{maxWidth:520,margin:"80px auto"}}><span className="kicker">BOEMO · Kitchen</span><h1>Kitchen sign in</h1><p>Use an authorized owner or staff account to manage food orders.</p><form className="adminForm" onSubmit={signIn}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<p role="alert">{error}</p>}<button className="button buttonPrimary" type="submit" disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form></section></div></main>
}