"use client";
import {GoogleAuthProvider,onAuthStateChanged,signInWithEmailAndPassword,signInWithPopup,signOut,type User} from "firebase/auth";
import {doc,getDoc} from "firebase/firestore";
import {useEffect,useState} from "react";
import {auth,db} from "@/lib/firebase/client";
export default function AdminGate({children}:{children:React.ReactNode}){
 const[user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true),[authorized,setAuthorized]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function checkAdmin(next:User){const role=await getDoc(doc(db,"admins",next.uid));const allowed=role.exists()&&["owner","staff"].includes(String(role.data().role));setAuthorized(allowed);return allowed}
 useEffect(()=>onAuthStateChanged(auth,async next=>{setUser(next);if(!next){setAuthorized(false);setChecking(false);return}try{const allowed=await checkAdmin(next);if(!allowed)await signOut(auth)}catch{setAuthorized(false);await signOut(auth)}finally{setChecking(false)}}),[]);
 async function finishSignIn(action:()=>Promise<User>){setBusy(true);setError("");try{const next=await action();if(!await checkAdmin(next)){setError("This account is not enabled for BOEMO Kitchen. Add this user's UID to the admins collection with role owner or staff.");await signOut(auth)} }catch(err){setError(err instanceof Error?err.message:"We could not sign you in. Check your details.")}finally{setBusy(false)}}
 async function signIn(e:React.FormEvent){e.preventDefault();await finishSignIn(async()=> (await signInWithEmailAndPassword(auth,email.trim(),password)).user)}
 async function google(){await finishSignIn(async()=> (await signInWithPopup(auth,new GoogleAuthProvider())).user)}
 if(checking)return <main className="adminPage"><div className="adminShell"><div className="emptyState"><div>🔐</div><h1>Opening BOEMO Kitchen</h1><p>Checking access…</p></div></div></main>;
 if(user&&authorized)return <div className="adminAuthorized"><div className="adminAccountBar"><span>BOEMO Kitchen · {user.email??"authorized staff"}</span><button className="button buttonLight" type="button" onClick={()=>void signOut(auth)}>Sign out</button></div>{children}</div>;
 return <main className="adminPage"><div className="adminShell"><section className="adminPanel" style={{maxWidth:520,margin:"80px auto"}}><span className="kicker">BOEMO · Kitchen</span><h1>Kitchen sign in</h1><p>Use an authorized owner or staff account to manage food orders.</p><button className="button buttonPrimary" type="button" onClick={()=>void google()} disabled={busy}>{busy?"Signing in…":"Continue with Google"}</button><div className="adminDivider">or</div><form className="adminForm" onSubmit={signIn}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="button buttonLight" type="submit" disabled={busy}>{busy?"Signing in…":"Sign in with email"}</button></form>{error&&<p role="alert" className="notice">{error}{user&&<><br/><small>Firebase UID: {user.uid}</small></>}</p>}</section></div></main>
}