"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import AdminGate from "@/app/admin/admin-gate";
import {deleteMenuItem,getBusinessSettings,getFoodOrders,getMenuItems,saveBusinessSettings,saveMenuItem,updateFoodOrderStatus,ORDER_STATUSES,type BusinessSettings,type FoodOrder,type MenuItem,type OrderStatus} from "@/lib/firebase/data";
function Dashboard(){
 const[orders,setOrders]=useState<FoodOrder[]>([]),[menu,setMenu]=useState<MenuItem[]>([]),[settings,setSettings]=useState<BusinessSettings>({id:"main",location:"",hours:"",locationNote:"",updatedAt:new Date().toISOString()}),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[tab,setTab]=useState<"orders"|"menu"|"location">("orders"),[menuDraft,setMenuDraft]=useState<MenuItem>({id:"",name:"",price:0,friendPrice:undefined,category:"Deal",description:"",available:true,preparationMinutes:15,sortOrder:0});
 async function load(){setLoading(true);try{const [ordersResult,menuResult,settingsResult]=await Promise.all([getFoodOrders(),getMenuItems(),getBusinessSettings()]);setOrders(ordersResult);setMenu(menuResult);if(settingsResult)setSettings(settingsResult)}catch{setNotice("BOEMO data could not be loaded. Check Firebase access and connectivity.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const active=useMemo(()=>orders.filter(o=>!["Collected","Delivered","Cancelled"].includes(o.status)),[orders]),deliveries=active.filter(o=>o.mode==="delivery"),today=new Date().toISOString().slice(0,10),todayCount=orders.filter(o=>o.scheduledFor.startsWith(today)).length;
 async function status(id:string,next:OrderStatus){try{await updateFoodOrderStatus(id,next);setOrders(current=>current.map(o=>o.id===id?{...o,status:next}:o))}catch{setNotice("Status update was not confirmed. Check connectivity and try again.")}}
 async function saveMenu(){if(!menuDraft.name.trim()||menuDraft.price<0){setNotice("Add a menu name and valid price.");return}const clean:MenuItem={id:menuDraft.id||crypto.randomUUID(),name:menuDraft.name.trim(),price:menuDraft.price,...(menuDraft.friendPrice===undefined?{}:{friendPrice:menuDraft.friendPrice}),category:menuDraft.category.trim()||"Deal",description:menuDraft.description.trim(),available:menuDraft.available,preparationMinutes:Math.max(0,menuDraft.preparationMinutes),sortOrder:Math.max(0,menuDraft.sortOrder)};try{await saveMenuItem(clean);setMenu(current=>[...current.filter(x=>x.id!==clean.id),clean].sort((a,b)=>a.sortOrder-b.sortOrder));setMenuDraft({id:"",name:"",price:0,friendPrice:undefined,category:"Deal",description:"",available:true,preparationMinutes:15,sortOrder:menu.length+1});setNotice("Menu saved.")}catch{setNotice("Menu could not be saved.")}}
 async function removeMenu(id:string){try{await deleteMenuItem(id);setMenu(current=>current.filter(x=>x.id!==id))}catch{setNotice("Menu item could not be deleted.")}}
 async function saveLocation(){try{const next={...settings,id:"main",updatedAt:new Date().toISOString()};await saveBusinessSettings(next);setSettings(next);setNotice("Kitchen location and hours saved.")}catch{setNotice("Business settings could not be saved.")}}
 return <main className="adminPage"><div className="adminShell"><div className="adminHeader"><div><span className="kicker">BOEMO · Kitchen Control</span><h1>Run the kitchen.</h1><p>Orders first. Menu, location and serving hours stay in your hands.</p></div><Link href="/" className="button buttonLight">View customer app</Link></div>{notice&&<div className="notice">{notice}</div>}<nav className="adminTabs"><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}>Orders</button><button className={tab==="menu"?"active":""} onClick={()=>setTab("menu")}>Menu</button><button className={tab==="location"?"active":""} onClick={()=>setTab("location")}>Location & Hours</button></nav>
 {tab==="orders"&&<><div className="stats"><article><span>Today</span><strong>{todayCount}</strong></article><article><span>Active</span><strong>{active.length}</strong></article><article><span>Delivery</span><strong>{deliveries.length}</strong></article><article><span>Ready</span><strong>{active.filter(o=>o.status==="Ready").length}</strong></article></div><section className="adminPanel"><div className="panelHeading"><h2>Kitchen queue</h2><button className="button buttonLight" type="button" onClick={()=>void load()}>Refresh</button></div>{loading?<div className="emptyState">Loading orders…</div>:active.length===0?<div className="emptyState">No active orders right now.</div>:<div className="queue">{active.map(order=><article className="queueRow" key={order.id}><div><strong>#{order.id.slice(0,8).toUpperCase()} · {order.customerName}</strong><small>{order.mode==="delivery"?"🚚 Delivery":"🛍️ Pickup"} · {new Date(order.scheduledFor).toLocaleString()}</small><small>{order.items.map(item=>item.quantity+"× "+item.name).join(" · ")} · P{order.total.toFixed(2)}</small>{order.mode==="delivery"&&<small>📍 {order.deliveryLocation}</small>}{order.instructions&&<small>Note: {order.instructions}</small>}</div><div className="queueActions"><strong>{order.status}</strong><select value={order.status} onChange={e=>void status(order.id,e.target.value as OrderStatus)}>{ORDER_STATUSES.map(value=><option key={value}>{value}</option>)}</select></div></article>)}</div>}</section></>}
 {tab==="menu"&&<section className="adminPanel"><div className="panelHeading"><h2>Menu control</h2><button className="button buttonLight" onClick={()=>setMenuDraft({id:"",name:"",price:0,friendPrice:undefined,category:"Deal",description:"",available:true,preparationMinutes:15,sortOrder:menu.length+1})}>New item</button></div><div className="adminTwoCol"><form className="adminForm" onSubmit={e=>{e.preventDefault();void saveMenu()}}><label>Name<input value={menuDraft.name} onChange={e=>setMenuDraft({...menuDraft,name:e.target.value})} required/></label><label>Price (P)<input type="number" min="0" step="0.01" value={menuDraft.price} onChange={e=>setMenuDraft({...menuDraft,price:Number(e.target.value)})}/></label><label>Bring-a-Friend price (optional)<input type="number" min="0" step="0.01" value={menuDraft.friendPrice??""} onChange={e=>setMenuDraft({...menuDraft,friendPrice:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>Category<input value={menuDraft.category} onChange={e=>setMenuDraft({...menuDraft,category:e.target.value})}/></label><label>Preparation minutes<input type="number" min="0" value={menuDraft.preparationMinutes} onChange={e=>setMenuDraft({...menuDraft,preparationMinutes:Number(e.target.value)})}/></label><label>Sort order<input type="number" min="0" value={menuDraft.sortOrder} onChange={e=>setMenuDraft({...menuDraft,sortOrder:Number(e.target.value)})}/></label><label>Description<textarea value={menuDraft.description} onChange={e=>setMenuDraft({...menuDraft,description:e.target.value})}/></label><label>Customer photo URL (optional)<input value={menuDraft.imageUrl??""} onChange={e=>setMenuDraft({...menuDraft,imageUrl:e.target.value})} placeholder="/boemo-assets/..." /></label><label className="checkRow"><input type="checkbox" checked={menuDraft.available} onChange={e=>setMenuDraft({...menuDraft,available:e.target.checked})}/> Available to customers</label><button className="button buttonPrimary" type="submit">Save menu item</button></form><div className="menuAdminList">{menu.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>P{item.price.toFixed(2)} · {item.available?"Available":"Hidden"}</small></div><div><button className="button buttonLight" onClick={()=>setMenuDraft(item)}>Edit</button><button className="button buttonDanger" onClick={()=>void removeMenu(item.id)}>Delete</button></div></article>)}</div></div></section>}
 {tab==="location"&&<section className="adminPanel"><h2>Where BOEMO is today</h2><p className="orderTruth">This is customer-facing information. Do not publish a location until it is actually correct.</p><form className="adminForm" onSubmit={e=>{e.preventDefault();void saveLocation()}}><label>Today&apos;s kitchen location<input value={settings.location} onChange={e=>setSettings({...settings,location:e.target.value})} placeholder="BAC campus / specific spot"/></label><label>Serving hours<input value={settings.hours} onChange={e=>setSettings({...settings,hours:e.target.value})} placeholder="e.g. 10:00–16:00"/></label><label>Location note / customer instruction<textarea value={settings.locationNote} onChange={e=>setSettings({...settings,locationNote:e.target.value})} placeholder="Look for the BOEMO mobile kitchen..."/></label><button className="button buttonPrimary" type="submit">Publish location & hours</button></form></section>}
 </div></main>
}
// Menu pricing, availability and customer-facing photos are controlled here.\nexport default function AdminPage(){return <AdminGate><Dashboard/></AdminGate>}
