"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import AdminGate from "@/app/admin/admin-gate";
import {getFoodOrders,updateFoodOrderStatus,ORDER_STATUSES,type FoodOrder,type OrderStatus} from "@/lib/firebase/data";
function Dashboard(){
 const[orders,setOrders]=useState<FoodOrder[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 async function load(){setLoading(true);try{setOrders(await getFoodOrders())}catch{setNotice("Orders could not be loaded. Previously cached data may still be available.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const active=useMemo(()=>orders.filter(o=>!["Collected","Delivered","Cancelled"].includes(o.status)),[orders]);const deliveries=active.filter(o=>o.mode==="delivery");const today=new Date().toISOString().slice(0,10);const todayCount=orders.filter(o=>o.scheduledFor.startsWith(today)).length;
 async function status(id:string,next:OrderStatus){try{await updateFoodOrderStatus(id,next);setOrders(current=>current.map(o=>o.id===id?{...o,status:next}:o))}catch{setNotice("Status update was not confirmed. Check connectivity and try again.")}}
 return <main className="adminPage"><div className="adminShell"><div className="adminHeader"><div><span className="kicker">BOEMO · Kitchen</span><h1>Today&apos;s orders.</h1><p>Keep the kitchen queue moving from New to pickup or delivery.</p></div><Link href="/" className="button buttonLight">View customer app</Link></div>{notice&&<div className="notice">{notice}</div>}<div className="stats"><article><span>Today</span><strong>{todayCount}</strong></article><article><span>Active</span><strong>{active.length}</strong></article><article><span>Delivery</span><strong>{deliveries.length}</strong></article><article><span>Ready</span><strong>{active.filter(o=>o.status==="Ready").length}</strong></article></div><section className="adminPanel"><div className="panelHeading"><h2>Kitchen queue</h2><button className="button buttonLight" type="button" onClick={()=>void load()}>Refresh</button></div>{loading?<div className="emptyState">Loading orders…</div>:active.length===0?<div className="emptyState">No active orders right now.</div>:<div className="queue">{active.map(order=><article className="queueRow" key={order.id}><div><strong>#{order.id.slice(0,8).toUpperCase()} · {order.customerName}</strong><small>{order.mode==="delivery"?"🚚 Delivery":"🛍️ Pickup"} · {new Date(order.scheduledFor).toLocaleString()}</small><small>{order.items.map(item=>item.quantity+"× "+item.name).join(" · ")} · P{order.total.toFixed(2)}</small>{order.mode==="delivery"&&<small>📍 {order.deliveryLocation}</small>}{order.instructions&&<small>Note: {order.instructions}</small>}</div><div className="queueActions"><strong>{order.status}</strong><select value={order.status} onChange={e=>void status(order.id,e.target.value as OrderStatus)}>{ORDER_STATUSES.map(value=><option key={value}>{value}</option>)}</select></div></article>)}</div>}</section></div></main>
}
export default function AdminPage(){return <AdminGate><Dashboard/></AdminGate>}