"use client";
import {useEffect,useState} from "react";
import {getIdToken,onAuthStateChanged} from "firebase/auth";
import {getToken,onMessage} from "firebase/messaging";
import {auth} from "@/lib/firebase/client";
import {getNotificationPreferences,isAdminUser,saveNotificationPreferences,saveNotificationToken,type NotificationPreferences} from "@/lib/firebase/data";
import {getMessagingInstance} from "@/lib/firebase/notifications";

const LEAD_OPTIONS=[5,10,15,20,30,45,60];
const FIREBASE_WEB_PUSH_PUBLIC_KEY="BHqdKto2WywPPoKMor2Qdl6E4QxcgOKLPDXSEwqyDAtjAYw_xazG646jc4jOol7sILe0roj-jwZG_ygrQ-Spuw0";

export default function NotificationSettings(){
 const[userUid,setUserUid]=useState<string|null>(null),[prefs,setPrefs]=useState<NotificationPreferences>({enabled:false,leadMinutes:15,updatedAt:""}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[admin,setAdmin]=useState(false);
 useEffect(()=>{const unsubscribeAuth=onAuthStateChanged(auth,async user=>{if(!user){setUserUid(null);return}setUserUid(user.uid);try{const [saved,isAdmin]=await Promise.all([getNotificationPreferences(user.uid),isAdminUser(user.uid)]);setPrefs(saved??{enabled:false,leadMinutes:15,updatedAt:""});setAdmin(isAdmin)}catch(error){console.warn("BOEMO notification settings unavailable",error)}});return unsubscribeAuth},[]);
 useEffect(()=>{let unsubscribeMessage:undefined|(()=>void);let cancelled=false;void (async()=>{try{if(!userUid||typeof window==="undefined"||!("Notification" in window)||Notification.permission!=="granted")return;const messaging=await getMessagingInstance();if(cancelled)return;unsubscribeMessage=onMessage(messaging,payload=>{const title=payload.notification?.title||"BOEMO pickup reminder";const body=payload.notification?.body||"Your BOEMO pickup is coming up.";const link=payload.fcmOptions?.link||payload.data?.link||"/account";void navigator.serviceWorker.ready.then(registration=>registration.showNotification(title,{body,icon:"/icon.svg",badge:"/icon.svg",tag:payload.data?.orderId?"boemo-pickup-"+payload.data.orderId:undefined,data:{link}})).catch(error=>console.warn("BOEMO foreground notification display unavailable",error))})}catch(error){console.warn("BOEMO foreground notifications unavailable",error)}})();return()=>{cancelled=true;unsubscribeMessage?.()}},[userUid]);
 async function enable(){if(!userUid)return;setBusy(true);setMessage("");try{if(!("Notification" in window)||!("serviceWorker" in navigator)){throw new Error("This browser does not support BOEMO push notifications.")}const permission=Notification.permission==="granted"?"granted":await Notification.requestPermission();if(permission!=="granted"){setMessage("Notifications are not enabled. You can allow them later in your browser/site settings.");return}const messaging=await getMessagingInstance();const registration=await navigator.serviceWorker.ready;const vapidKey=FIREBASE_WEB_PUSH_PUBLIC_KEY;const token=await getToken(messaging,{vapidKey,serviceWorkerRegistration:registration});if(!token)throw new Error("BOEMO could not register this device for notifications.");await saveNotificationToken(userUid,token,admin);const next={...prefs,enabled:true,updatedAt:new Date().toISOString()};await saveNotificationPreferences(userUid,next);setPrefs(next);setMessage("Notifications are enabled on this device.")}catch(error){setMessage(error instanceof Error?error.message:"Notifications could not be enabled.")}finally{setBusy(false)}}
 async function testNotification(){if(!userUid)return;setBusy(true);setMessage("");try{const user=auth.currentUser;if(!user)throw new Error("Your BOEMO session is no longer signed in.");const idToken=await getIdToken(user,true);const response=await fetch("/api/notifications/test",{method:"POST",headers:{Authorization:"Bearer "+idToken}});const result=await response.json() as {sent?:boolean;error?:string};if(!response.ok||!result.sent)throw new Error(result.error||"BOEMO could not send the test notification.");setMessage("Test notification sent. Check this device now.");}catch(error){setMessage(error instanceof Error?error.message:"Test notification could not be sent. Check your notification setup.")}finally{setBusy(false)}}
 async function saveLead(value:number){if(!userUid)return;setBusy(true);setMessage("");try{const next={...prefs,leadMinutes:value,updatedAt:new Date().toISOString()};await saveNotificationPreferences(userUid,next);setPrefs(next);setMessage("BOEMO will remind you "+value+" minutes before pickup.")}catch{setMessage("Notification timing could not be saved.")}finally{setBusy(false)}}
 if(!userUid)return null;
 return <section className="notificationSettings"><div className="panelHeading"><div><span className="kicker">Settings · Notifications</span><h2>Pickup reminders.</h2></div><span className="orderTruth">{prefs.enabled?"Enabled on this device":"Not enabled"}</span></div><p>Choose when BOEMO should remind you before a scheduled pickup. The default is 15 minutes. Notifications are only sent after you give this device permission.</p>{!prefs.enabled?<button className="button buttonPrimary" type="button" onClick={()=>void enable()} disabled={busy}>{busy?"Setting up…":"Enable pickup notifications"}</button>:<><div className="notificationChoice"><label>Remind me before pickup<select value={prefs.leadMinutes} onChange={e=>void saveLead(Number(e.target.value))} disabled={busy}>{LEAD_OPTIONS.map(value=><option key={value} value={value}>{value} minutes before</option>)}</select></label></div><p className="orderTruth">{admin?"As kitchen staff, this device can receive reminders for upcoming BOEMO pickup orders.":"This device can receive reminders for your BOEMO pickup orders."} When a reminder appears, tapping it opens My BOEMO so you can see your saved orders. It does not change, cancel or resubmit the order.</p><button className="button buttonLight" type="button" onClick={()=>void testNotification()} disabled={busy}>{busy?"Sending test…":"Send a test notification"}</button></>}{message&&<p className="notice" role="status">{message}</p>}</section>;
}