export type ReceiptOrder={id:string;createdAt:string;customerName:string;phone:string;mode:"pickup"|"delivery";scheduledFor:string;deliveryLocation:string;instructions:string;items:{name:string;price:number;quantity:number}[];total:number;status:string};
function escapePdf(value:string){return value.replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)")}
function wrap(value:string,max=62){if(!value)return [];const words=value.split(/\s+/);const lines:string[]=[];let line="";for(const word of words){if((line+" "+word).trim().length>max&&line){lines.push(line);line=word}else line=(line+" "+word).trim()}if(line)lines.push(line);return lines}
export function downloadReceiptPdf(order:ReceiptOrder){
 const lines:Array<[string,number]>=[["BOEMO JOOS FOOD DEALS",18],["Order receipt",12],["",10],["Reference #"+order.id.slice(0,8).toUpperCase(),10],["Customer: "+order.customerName,10],["Phone: "+order.phone,10],["Type: "+(order.mode==="delivery"?"Delivery":"Pickup"),10],["Requested: "+new Date(order.scheduledFor).toLocaleString(),10],...(order.mode==="delivery"&&order.deliveryLocation?[["Location: "+order.deliveryLocation,10] as [string,number]]:[]),["",10],["Items",12],...order.items.map(item=>[item.quantity+" x "+item.name+" — P"+item.price.toFixed(2),10] as [string,number]),["",10],["TOTAL: P"+order.total.toFixed(2),14],["Status: "+order.status,10],["",10],...wrap(order.instructions?"Instructions: "+order.instructions:"").map(x=>[x,10] as [string,number]),["",10],["Thank you for choosing BOEMO.",10]];
 const pageHeight=842;let y=800;const content:string[]=[];for(const [raw,size] of lines){if(!raw){y-=12;continue}content.push("BT /F1 "+size+" Tf 50 "+y+" Td ("+escapePdf(raw)+") Tj ET");y-=size+9;if(y<50)break}
 const stream=content.join("\n");const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 "+pageHeight+"] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Length "+stream.length+" >>\nstream\n"+stream+"\nendstream"];
 let pdf="%PDF-1.4\n";const offsets:number[]=[];objects.forEach((obj,i)=>{offsets[i+1]=pdf.length;pdf+=(i+1)+" 0 obj\n"+obj+"\nendobj\n"});const xref=pdf.length;pdf+="xref\n0 "+(objects.length+1)+"\n0000000000 65535 f \n";for(let i=1;i<=objects.length;i++)pdf+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";pdf+="trailer\n<< /Size "+(objects.length+1)+" /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF";
 const blob=new Blob([pdf],{type:"application/pdf"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="boemo-receipt-"+order.id.slice(0,8).toUpperCase()+".pdf";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);
}
