"use client";
import Link from "next/link";
import {GoogleAuthProvider,linkWithPopup,onAuthStateChanged,signInWithPopup,signOut,type User} from "firebase/auth";
import {useEffect,useState} from "react";
import {auth} from "@/lib/firebase/client";
import {getCustomerProfile,isAdminUser,saveCustomerProfile,type CustomerProfile} from "@/lib/firebase/data";
export default function AccountPage(){
 const[user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<CustomerProfile|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>onAuthStateChanged(auth,async next=>{if(next&&await isAdminUser(next.uid)){await signOut(auth);setUser(null);setProfile(null);return}setUser(next);if(next){try{const saved=await getCustomerProfile(next.uid);setProfile(saved??{uid:next.uid,name:next.displayName??"",email:next.email??"",phone:"",preferredDeliveryLocation:"",notes:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}catch(error){console.warn("BOEMO customer profile unavailable",error);setProfile({uid:next.uid,name:next.displayName??"",email:next.email??"",phone:"",preferredDeliveryLocation:"",notes:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}}else setProfile(null)}),[]);
 async function google(){setBusy(true);setMessage("");try{const provider=new GoogleAuthProvider();if(user?.isAnonymous){await linkWithPopup(user,provider)}else if(!user){const result=await signInWithPopup(auth,provider);const saved=await getCustomerProfile(result.user.uid);if(!saved)setProfile({uid:result.user.uid,name:result.user.displayName??"",email:result.user.email??"",phone:"",preferredDeliveryLocation:"",notes:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}setMessage("Google sign-in is connected to your BOEMO account.")}catch(error){setMessage(error instanceof Error?error.message:"Google sign-in could not be completed.")}finally{setBusy(false)}}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!user||!profile)return;setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const next={...profile,name:String(form.get("name")??"").trim(),email:String(form.get("email")??"").trim(),phone:String(form.get("phone")??"").trim(),preferredDeliveryLocation:String(form.get("preferredDeliveryLocation")??"").trim(),notes:String(form.get("notes")??"").trim(),updatedAt:new Date().toISOString()};try{await saveCustomerProfile(next);setProfile(next);setMessage("Your BOEMO details are saved.")}catch{setMessage("We could not save your details. Please try again.")}finally{setBusy(false)}}
 return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="logo"><span className="logoMark">B</span><span>BOEMO</span></Link><Link href="/order" className="button buttonLight">Order food</Link></div><section className="orderCard" style={{maxWidth:680,margin:"0 auto"}}><span className="kicker">Your BOEMO account</span><h1>Save your details.</h1><p>Ordering stays available as a guest. Your account simply makes repeat orders faster.</p>{!user&&<div className="actions"><button className="button buttonPrimary" type="button" onClick={()=>void google()} disabled={busy}>Continue with Google</button></div>}{user&&profile&&<form className="adminForm" onSubmit={save}><label>Name<input name="name" defaultValue={profile.name} autoComplete="name" required/></label><label>Email<input name="email" type="email" defaultValue={profile.email} autoComplete="email" readOnly={Boolean(user.email)}/></label><label>WhatsApp / phone<input name="phone" type="tel" defaultValue={profile.phone} autoComplete="tel" required/></label><label>Preferred delivery location <span>(optional)</span><input name="preferredDeliveryLocation" defaultValue={profile.preferredDeliveryLocation}/></label><label>Notes <span>(optional)</span><textarea name="notes" defaultValue={profile.notes}/></label><button className="button buttonPrimary" type="submit" disabled={busy}>{busy?"Saving…":"Save my BOEMO details"}</button></form>}{message&&<p className="notice" role="status">{message}</p>}{user&&<button className="button buttonLight" type="button" onClick={()=>void signOut(auth)}>Sign out</button>}<p className="orderTruth">Guest ordering never requires authentication. A guest Firebase session can be upgraded to Google sign-in later without losing the saved profile.</p></section></div></main>;
}